sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
  - cd docs
  - bundle install
  - npm install
notifications:
  slack:
    on_success: change
    on_failure: always
